name: Delete untagged
on:
  registry_package:
  workflow_dispatch:

permissions:
  actions: write
  packages: write

jobs:
  delete-untagged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'silverblue'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
